### ISSUE TITLE
how can i change the size of the scaning area?

### ISSUE THREAD

**Issue by LimLLL** [phamxtien/streamlit_qrcode_scanner#2]
the current frame of the scanning area is more like, uh... suit for a bar QR code rather than a square QR code. Im not really familiar with the js language, it would be so appreciated if you could just indicate where should I modify to change the shape of the scanning area

**Comment by phamxtien** [comment]
> the current frame of the scanning area is more like, uh... suit for a bar QR code rather than a square QR code. Im not really familiar with the js language, it would be so appreciated if you could just indicate where should I modify to change the shape of the scanning area

It can use for barcode and qrcode

**Comment by phamxtien** [comment]
You can change on line 84 of main.js
       const config = { fps: 10, qrbox: { width: 2*(height-10), height: height-10 } };  

to

        const config = { fps: 10, qrbox: { width: height-10, height: height-10 } };

**Comment by LimLLL** [comment]
> You can change on line 84 of main.js        const config = { fps: 10, qrbox: { width: 2*(height-10), height: height-10 } };  
> 
> to
> 
>         const config = { fps: 10, qrbox: { width: height-10, height: height-10 } };

thank you so much

**Comment by CHerSun** [comment]
@phamxtien could this be made configurable from Python?

**Comment by phamxtien** [comment]
> @phamxtien could this be made configurable 
Currently, i do not know how to make it from python :)
