### ISSUE TITLE
Any sign on camera not working

### ISSUE THREAD

**Issue by CHerSun** [phamxtien/streamlit_qrcode_scanner#4]
Hi.

I've tried your component and had a hard time figuring out what's happening - just a blank page. It would be awesome to show something in such case, like no camera permissions or whatever.

(P.S.: the struggle was with HTTP localhost dev page, browsers don't want to give camera access over http, but still lack of any sign is, well, misleading; st.camera_input shows the grayed out frame, which is quite obvious)

**Comment by phamxtien** [comment]
> Hi.
> 
> I've tried your component and had a hard time figuring out what's happening - just a blank page. It would be awesome to show something in such case, like no camera permissions or whatever.
> 
> (P.S.: the struggle was with HTTP localhost dev page, browsers don't want to give camera access over http, but still lack of any sign is, well, misleading; st.camera_input shows the grayed out frame, which is quite obvious)

It's not work with http, please use https.

**Comment by CHerSun** [comment]
Yep, that's exactly what I wrote. But it's very misleading to not have any sign of component at all. Anything would be nice, grayed out frame, some message, anything really.
